In [1]:
import pandas as pd
import numpy as np
import requests
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import csv

# Section 1: Zillow Housing Data


In [109]:
zhvi_3brm = pd.read_csv('zillow_data.csv')

In [110]:
zhvi_3brm.shape

(18458, 280)

In [117]:
zhvi_3brm.head()

RegionID  SizeRank   RegionName RegionType StateName State  \
0      6181         0     New York       city        NY    NY   
1     12447         1  Los Angeles       city        CA    CA   
2     39051         2      Houston       city        TX    TX   
3     17426         3      Chicago       city        IL    IL   
4      6915         4  San Antonio       city        TX    TX   

                                   Metro          CountyName  2000-01-31  \
0  New York-Newark-Jersey City, NY-NJ-PA       Queens County    244993.0   
1     Los Angeles-Long Beach-Anaheim, CA  Los Angeles County    228623.0   
2   Houston-The Woodlands-Sugar Land, TX       Harris County     99808.0   
3     Chicago-Naperville-Elgin, IL-IN-WI         Cook County    160643.0   
4          San Antonio-New Braunfels, TX        Bexar County    102255.0   

   2000-02-29  ...  2021-11-30  2021-12-31  2022-01-31  2022-02-28  \
0    246745.0  ...    708040.0    711549.0    715775.0    720637.0   
1    228794.0  ...    893402.0    899121.0    904265.0    913104.0   
2     99844.0  ...    227481.0    230208.0    233037.0    236333.0   
3    160951.0  ...    304296.0    306968.0    309531.0    311054.0   
4    102416.0  ...    241410.0    245654.0    249856.0    253847.0   

   2022-03-31  2022-04-30  2022-05-31  2022-06-30  2022-07-31  2022-08-31  
0    726757.0    732698.0    739633.0    744904.0    749033.0    751137.0  
1    928696.0    947698.0    964530.0    966200.0    965512.0    950327.0  
2    240567.0    245106.0    249391.0    252562.0    254626.0    255900.0  
3    313336.0    315071.0    318527.0    321029.0    322421.0    321973.0  
4    258904.0    263939.0    268412.0    271147.0    272190.0    272533.0  

[5 rows x 280 columns]

In [133]:
for x in zhvi_3brm.columns[9:]:
    i = zhvi_3brm.columns.get_loc(x)
    if i+1>279:
        break
    else:
        zhvi_3brm.iloc[:,9] = zhvi_3brm.iloc[:,9].fillna(zhvi_3brm.iloc[:, i+1])



2000-02-29
9
0        246745.0
1        228794.0
2         99844.0
3        160951.0
4        102416.0
           ...   
18453    195917.0
18454     60521.0
18455     41898.0
18456     79299.0
18457    124116.0
Name: 2000-02-29, Length: 18458, dtype: float64
0        248333.0
1        229873.0
2         99688.0
3        161657.0
4        102485.0
           ...   
18453         NaN
18454         NaN
18455         NaN
18456         NaN
18457         NaN
Name: 2000-03-31, Length: 18458, dtype: float64
2000-03-31
10
0        246745.0
1        228794.0
2         99844.0
3        160951.0
4        102416.0
           ...   
18453    195917.0
18454     60521.0
18455     41898.0
18456     79299.0
18457    124116.0
Name: 2000-02-29, Length: 18458, dtype: float64
0        251316.0
1        231866.0
2         99752.0
3        162874.0
4        102633.0
           ...   
18453         NaN
18454         NaN
18455         NaN
18456         NaN
18457         NaN
Name: 2000-04-30, Length: 18458, dtyp

Name: 2005-10-31, Length: 18458, dtype: float64
2005-10-31
77
0        246745.0
1        228794.0
2         99844.0
3        160951.0
4        102416.0
           ...   
18453    195917.0
18454     60521.0
18455     41898.0
18456     79299.0
18457    124116.0
Name: 2000-02-29, Length: 18458, dtype: float64
0        493507.0
1        591632.0
2        122767.0
3        280875.0
4        119367.0
           ...   
18453         NaN
18454         NaN
18455         NaN
18456         NaN
18457         NaN
Name: 2005-11-30, Length: 18458, dtype: float64
2005-11-30
78
0        246745.0
1        228794.0
2         99844.0
3        160951.0
4        102416.0
           ...   
18453    195917.0
18454     60521.0
18455     41898.0
18456     79299.0
18457    124116.0
Name: 2000-02-29, Length: 18458, dtype: float64
0        500437.0
1        598754.0
2        122735.0
3        283440.0
4        119716.0
           ...   
18453         NaN
18454         NaN
18455         NaN
18456         NaN
18457 

Name: 2010-05-31, Length: 18458, dtype: float64
2010-05-31
132
0        246745.0
1        228794.0
2         99844.0
3        160951.0
4        102416.0
           ...   
18453    195917.0
18454     60521.0
18455     41898.0
18456     79299.0
18457    124116.0
Name: 2000-02-29, Length: 18458, dtype: float64
0        455321.0
1        426608.0
2        120552.0
3        224149.0
4        128285.0
           ...   
18453    187346.0
18454         NaN
18455         NaN
18456     77707.0
18457    123747.0
Name: 2010-06-30, Length: 18458, dtype: float64
2010-06-30
133
0        246745.0
1        228794.0
2         99844.0
3        160951.0
4        102416.0
           ...   
18453    195917.0
18454     60521.0
18455     41898.0
18456     79299.0
18457    124116.0
Name: 2000-02-29, Length: 18458, dtype: float64
0        457185.0
1        424550.0
2        119653.0
3        220388.0
4        128183.0
           ...   
18453    183696.0
18454         NaN
18455         NaN
18456     78353.0
1845

2015-06-30
193
0        246745.0
1        228794.0
2         99844.0
3        160951.0
4        102416.0
           ...   
18453    195917.0
18454     60521.0
18455     41898.0
18456     79299.0
18457    124116.0
Name: 2000-02-29, Length: 18458, dtype: float64
0        522183.0
1        536904.0
2        146789.0
3        219684.0
4        145764.0
           ...   
18453    230943.0
18454     59775.0
18455         NaN
18456     87903.0
18457    148538.0
Name: 2015-07-31, Length: 18458, dtype: float64
2015-07-31
194
0        246745.0
1        228794.0
2         99844.0
3        160951.0
4        102416.0
           ...   
18453    195917.0
18454     60521.0
18455     41898.0
18456     79299.0
18457    124116.0
Name: 2000-02-29, Length: 18458, dtype: float64
0        525200.0
1        537436.0
2        147169.0
3        219968.0
4        147203.0
           ...   
18453    233060.0
18454     59754.0
18455         NaN
18456     88349.0
18457    149111.0
Name: 2015-08-31, Length: 18458, d

Name: 2020-09-30, Length: 18458, dtype: float64
2020-09-30
256
0        246745.0
1        228794.0
2         99844.0
3        160951.0
4        102416.0
           ...   
18453    195917.0
18454     60521.0
18455     41898.0
18456     79299.0
18457    124116.0
Name: 2000-02-29, Length: 18458, dtype: float64
0        661725.0
1        757041.0
2        190320.0
3        273686.0
4        198506.0
           ...   
18453    332172.0
18454     76127.0
18455         NaN
18456    103223.0
18457    203025.0
Name: 2020-10-31, Length: 18458, dtype: float64
2020-10-31
257
0        246745.0
1        228794.0
2         99844.0
3        160951.0
4        102416.0
           ...   
18453    195917.0
18454     60521.0
18455     41898.0
18456     79299.0
18457    124116.0
Name: 2000-02-29, Length: 18458, dtype: float64
0        664807.0
1        764825.0
2        192692.0
3        276602.0
4        200632.0
           ...   
18453    334491.0
18454     76745.0
18455         NaN
18456    103747.0
1845

In [132]:
zhvi_3brm.isnull().sum()

RegionID        0
SizeRank        0
RegionName      0
RegionType      0
StateName       0
             ... 
2022-04-30    258
2022-05-31    215
2022-06-30    153
2022-07-31     93
2022-08-31     12
Length: 280, dtype: int64

In [123]:
zhvi_3brms = zhvi_3brm[['RegionID', 'RegionName', 'State', 'CountyName', '2000-01-31', '2022-08-31']]
zhvi_3brms = zhvi_3brms.rename(columns = {'2000-01-31':'year1', '2022-08-31':'year2'})

In [124]:
def percent_change(col1, col2):
    return (col2 - col1)/col1

In [125]:
zhvi_3brms['percent_change'] = zhvi_3brms.apply(lambda x: percent_change(x.year1, x.year2), axis=1)

In [104]:
zhvi_3brms['city'] = zhvi_3brms['RegionName'].apply(lambda row: row.rstrip('County'))

In [126]:
zhvi_3brms

RegionID        RegionName State          CountyName     year1  \
0          6181          New York    NY       Queens County  244993.0   
1         12447       Los Angeles    CA  Los Angeles County  228623.0   
2         39051           Houston    TX       Harris County   99808.0   
3         17426           Chicago    IL         Cook County  160643.0   
4          6915       San Antonio    TX        Bexar County  102255.0   
...         ...               ...   ...                 ...       ...   
18453     47188    Poncha Springs    CO      Chaffee County       NaN   
18454      6427           Parsons    WV       Tucker County       NaN   
18455     52717            Junior    WV      Barbour County       NaN   
18456     54589  Strawberry Point    IA      Clayton County       NaN   
18457     22420     Medicine Park    OK     Comanche County       NaN   

          year2  percent_change  
0      751137.0        2.065953  
1      950327.0        3.156743  
2      255900.0        1.563923  
3      321973.0        1.004277  
4      272533.0        1.665229  
...         ...             ...  
18453  444590.0             NaN  
18454   98740.0             NaN  
18455   51025.0             NaN  
18456  121865.0             NaN  
18457  264322.0             NaN  

[18458 rows x 7 columns]

# Section 2: Training & Testing

In [8]:
# https://www.businessinsider.com/most-miserable-cities-in-the-united-states-based-on-data-2019-9
bi_raw = pd.read_csv('training_cities.csv', header = 1)[['City', 'State', 'WEIGHTED Z-SCORE']].dropna()

In [9]:
bi_raw.head()

City       State  WEIGHTED Z-SCORE
0         Gary     Indiana         -1.313482
1  Port Arthur       Texas         -1.262623
2      Detroit    Michigan         -1.223281
3      Passaic  New Jersey         -1.174955
4       Newark  New Jersey         -1.138656

In [97]:
bi_final = bi_raw.rename(columns = {'City': 'city', 'State':'state', 'WEIGHTED Z-SCORE': 'z'})

In [19]:
bi_raw

city       state         z
0           Gary     Indiana -1.313482
1    Port Arthur       Texas -1.262623
2        Detroit    Michigan -1.223281
3        Passaic  New Jersey -1.174955
4         Newark  New Jersey -1.138656
..           ...         ...       ...
990         Kyle       Texas  2.197704
991       Frisco       Texas  2.454678
992   Little Elm       Texas  3.247657
993      Leander       Texas  3.930241
994     Herriman        Utah  4.125790

[995 rows x 3 columns]

In [98]:
bi_final['label'] = bi_raw.apply(lambda row: 1 if row.z >= -0.057849734 else 0, axis = 1)
bi_final['city_state'] = bi_final[['city', 'state']].agg(' '.join, axis=1)

In [99]:
bi_final = bi_final[['city', 'state', 'city_state', 'z' ,'label']]

In [100]:
bi_final

city       state          city_state         z  label
0           Gary     Indiana        Gary Indiana -1.313482      0
1    Port Arthur       Texas   Port Arthur Texas -1.262623      0
2        Detroit    Michigan    Detroit Michigan -1.223281      0
3        Passaic  New Jersey  Passaic New Jersey -1.174955      0
4         Newark  New Jersey   Newark New Jersey -1.138656      0
..           ...         ...                 ...       ...    ...
990         Kyle       Texas          Kyle Texas  2.197704      1
991       Frisco       Texas        Frisco Texas  2.454678      1
992   Little Elm       Texas    Little Elm Texas  3.247657      1
993      Leander       Texas       Leander Texas  3.930241      1
994     Herriman        Utah       Herriman Utah  4.125790      1

[995 rows x 5 columns]

# Section 3: News API

In [52]:
def counter(string, counts):
    x = string.split()
    count = 0
    for i in x:
        if i in counts:
            count += 1
    return count
    

In [23]:
endpoint="https://newsapi.org/v2/everything"

In [73]:
positives = ['positive', 'good', 'forward-looking', 
             'productive', 'best', 'finest', 
            'first rate', 'perfect', 'terrific', 'leading', 'optimal', 
             'primo', 'first class', 'greatest']
negatives = ['negative', 'unproductive', 'impotent', 'useless', 
            'disadvantageous', 'unhelpful', 'doubtful', 'fruitless', 'bad', 
             'worst', 'inferior', 'incorrect', 'not right', 'unfavorable']



In [78]:
results = []


for x in bi_final['city_state'][50:100]:
    URLPost = {'apiKey':'9309e7598f994f3e9f2fc16858a4796c',
            'q':x} #Replace your with your own API key from https://newsapi.org/docs/get-started
    response=requests.get(endpoint, URLPost)
    jsontxt = response.json()
    try:
        if jsontxt['totalResults'] == 0:
            results.append(0)
            continue
        else:
            p = 0
            n = 0
            for i in range(0, 100):
                k = jsontxt['articles'][i]['description']
                p += counter(k, positives)
                n += counter(k, negatives)
            results.append(p/(n+p))
    except:
        results.append(0)
        continue
        
bi_final['score'] = results

In [102]:
bi_first_50 = bi_final.head(50)

# Section 4: Simple Neural Network

In [148]:
def activation_base(x):
    e = 2.718281828459045
    return 1/(1+e**(-x))

activation = np.vectorize(activation_base)

def z_1(x, w1, b1):
    return np.dot(x, w1) + b1


def z_2(z, w2, b2):
    return np.dot(z, w2) + b2

def network(x, w1, b1, w2, b2):
    z1 = z_1(x, w1, b1)
    h = activation(z1)
    z2 = z_2(h, w2, b2)
    yhat = activation(z2)
    return [yhat, z1, z2]

def loss(hat, y):
    return .5*(hat - y)**2
loss_vect = np.vectorize(loss)

def der_sig(x):
    return x*(1-x)
der_sig_vect = np.vectorize(der_sig)

def hat(hats, y):
    return (hats - y)

hat_vect = np.vectorize(hat)

def identity_values(size, x):
    #returns identity matrix of size size with 1's replaced by x values, x should be sizex1 
    return np.identity(size)*np.asarray(x)

def matrix_gb(z1, w2):
    #helper matrix for partial derivatives
    zt = z1.transpose()
    sig = der_sig_vect(activation(zt))
    final = w2.transpose().dot(sig)
    return final.transpose()

def matrix_red(hats, y, Z2):
    #helper matrix for partial derivatives
    yhat = hat_vect(hats, y)
    sigz = identity_values(Z2.shape[0], der_sig_vect(activation(Z2)))
    return identity_values(Z2.shape[0], sigz.dot(yhat))

def dW1(x, w1, gb, r, lr):
    xt = x.transpose()
    final = xt.dot(r.dot(gb))*lr
    return w1-final

def dW2(z1, r, LR, W2):
    h = activation(z1)
    i = np.sum(r.dot(h), axis = 0)
    final = LR*i.transpose()
    return W2-final

def dB(gb, r, LR, B):
    final = np.sum(r.dot(gb), axis = 0)*LR
    return B-final

def dC(r, LR, c):
    final = np.sum(r)*LR
    return c-final

In [198]:
def full_network(x, w1, b1, w2, b2, lr, y, epoc, report):
    k = 0
    results = network(x, w1, b1, w2, b2)
    l = loss_vect(results[0], y)
    print("result vector of epoc "+str(k)+ " is \n"+str(results[0]))
    print("Mean loss of epoc "+str(k)+ " is \n"+str(np.mean(l)))
    print("Total loss of epoc "+str(k)+ " is \n"+str(np.sum(l)))
    ml = [np.mean(l)]
    sl = [np.sum(l)]
    while k <= epoc:
        gb = matrix_gb(results[1], w2)
        #print("GB matrix at epoc "+str(k)+ " is \n"+ str(gb.shape))
        
        red = matrix_red(results[0], y, results[2])
        #print("red matrix at epoc "+str(k)+ " is \n"+ str(red.shape))
        
        w1 = dW1(x, w1, gb, red, lr)
        if k % report == 0:
            print("w1 matrix at epoc "+str(k)+ " is \n"+ str(w1))
        
        w2 = dW2(results[1], red, lr, w2)
        if k % report == 0:
            print("w2 matrix at epoc "+str(k)+ " is \n"+ str(w2))
        
        b1 = dB(gb, red, lr, b1)
        if k % report == 0:
            print("b1 matrix at epoc "+str(k)+ " is \n"+ str(b1))
        
        b2 = dC(red, lr, b2)
        if k % report == 0:
            print("c matrix at epoc "+str(k)+ " is \n"+ str(b2))
        
        results = network(x, w1, b1, w2, b2)
        
        l = loss_vect(results[0], y)
        if k % report == 0:
            print("result vector of epoc "+str(k)+ " is \n"+str(results[0]))
            print("loss vector of epoc "+str(k)+ " is \n"+str(l))
            print("Mean loss of epoc "+str(k)+ " is \n"+str(np.mean(l)))
            print("Total loss of epoc "+str(k)+ " is \n"+str(np.sum(l)))
        ml.append(np.mean(l))
        sl.append(np.sum(l))
        k += 1
    return [ml, sl, results[0]]

In [136]:
tester = bi_first_50[['city','city_state', 'z', 'score', 'label']]


In [230]:
tester.to_csv('tester.csv')

In [178]:
weight1 = np.random.rand(2, 2)
weight1.shape
weight2 = np.random.rand(2, 1)
bias1 = np.random.rand(1, 2)
bias2 = np.random.rand(1, 1)

In [179]:
print(x_train.shape)
print(weight1.shape)
print(weight2.shape)
print(bias1.shape)
print(bias2.shape)
print(y_train.shape)

(40, 2)
(2, 2)
(2, 1)
(1, 2)
(1, 1)
(40, 1)


In [204]:
x = tester[['z', 'score',]]
y = tester['label']

In [205]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [206]:
y_trainm = np.matrix(y_train.values.reshape(40,1))
x_trainm = np.matrix(x_train.values.reshape(40,2))

### Section 4.1: Results

In [199]:
results = full_network(x_trainm, weight1, bias1, weight2, bias2, .1, y_trainm ,100, 10)

result vector of epoc 0 is 
[[0.63091002]
 [0.6356906 ]
 [0.63742201]
 [0.63603677]
 [0.62989272]
 [0.63569934]
 [0.63207627]
 [0.63226571]
 [0.63776898]
 [0.63102458]
 [0.63049659]
 [0.63665352]
 [0.63692819]
 [0.63186514]
 [0.63734908]
 [0.63468053]
 [0.63220996]
 [0.63712745]
 [0.63186512]
 [0.63011153]
 [0.63176693]
 [0.63617092]
 [0.63191839]
 [0.62936611]
 [0.63133499]
 [0.63520246]
 [0.63216105]
 [0.63187371]
 [0.63139888]
 [0.63752826]
 [0.63060645]
 [0.63134911]
 [0.63129499]
 [0.63781217]
 [0.63131522]
 [0.63024971]
 [0.6321567 ]
 [0.63654525]
 [0.63723476]
 [0.63200812]]
Mean loss of epoc 0 is 
0.20062318366852558
Total loss of epoc 0 is 
8.024927346741023
w1 matrix at epoc 0 is 
[[0.22491887 0.56788125]
 [0.04295281 0.66361134]]
w2 matrix at epoc 0 is 
[[ 0.50318058]
 [-0.35779659]]
b1 matrix at epoc 0 is 
[[-0.06785194  0.76356964]]
c matrix at epoc 0 is 
[[-0.46160008]]
result vector of epoc 0 is 
[[0.39107248]
 [0.37977458]
 [0.3787451 ]
 [0.37955161]
 [0.39199884]
 [0.3

In [219]:
[x] = results[2].transpose().tolist()

In [222]:
con = pd.DataFrame({'guess':x, 'actual':y_train})
con['guess_com'] = con.apply(lambda row: 1 if row.guess >= .5 else 0, axis = 1)

In [225]:
confusion_matrix(con['actual'],con['guess_com'])

array([[40]])